# frozen_string_literal: true

module Niwa
  module Helpers
    # Helper to render main component
    module MainHelper
      # Render tree from navigation
      # rubocop:disable Metrics/MethodLength
      def render_main(registry)
        html = "<div class='main'>"
        registry.each do |item|
          html << <<~HTML
            <div id='niwa-item-#{item.id}' class='item'>
              <h2 class='item__title'>#{item.klass}##{item.name}</h2>
              <div class='item__body'>
              <p class='item__plugin'>Generated by: #{item.plugin_name}</p>
              <p class='item__filename'>Defined in: #{item.filename}</p>
              <p class='item__metadata'>Metadata: #{item.metadata}</p>
          HTML
          html << <<~BODY
            <details>
              <summary>Details</summary>
              <code>
                @fake.code
              </code>
            </details>
          BODY
          html << '</div>'
          html << '</div>'
          html << '<hr>'
        end
        html << '</div>'
        html
      end
      # rubocop:enable Metrics/MethodLength
    end
  end
end
